// MLCommons AIRR Single-Turn Inference-Time Prompt Attack Taxonomy (v0.7.0)
// Complete Data Manifest: 113 Cataloged Attacks, 4 Families, 8 Categories, 18 Atomic Leaves

export interface CatalogAttack {
  id: string;
  name: string;
  family: 'Perturbation' | 'Composition & Ordering' | 'Encoding Abuse' | 'Overt Carriers';
  category: string;
  leaf: string;
  venue: string;
  year: number;
  modelsTested?: string;
  prevalence: string;
  mechanismSnippet?: string;
}

export interface LeafDefinition {
  id: string;
  name: string;
  category: string;
  family: 'Perturbation' | 'Composition & Ordering' | 'Encoding Abuse' | 'Overt Carriers';
  prevalence: number; // percentage e.g. 23.89
  attackCount: number;
  era: number; // e.g. 2024.8
  sophistication: number; // 0-10 scale
  coords: {
    stealth: number;       // X: 0-10
    automation: number;    // Y: 0-10
    distortion: number;    // Z: 0-10
  };
  summary: string;
}

export interface FamilyDefinition {
  id: 'perturbation' | 'composition' | 'encoding' | 'overt';
  name: 'Perturbation' | 'Composition & Ordering' | 'Encoding Abuse' | 'Overt Carriers';
  prevalence: number;
  attackCount: number;
  categoryCount: number;
  leafCount: number;
  strategy: string;
  definition: string;
  code: string;
  radarScores: number[]; // [Prevalence, Automation, Transfer, Stealth, Resistance, Scalability]
}

export interface HybridBridge {
  id: string;
  name: string;
  familyA: string;
  leafA: string;
  familyB: string;
  leafB: string;
  description: string;
  citation: string;
}

export const RADAR_AXES = [
  'Empirical Prevalence',
  'Algorithmic Automation',
  'Cross-Model Transferability',
  'Evasion Stealth',
  'Resistance to Alignment',
  'Exploration Scalability',
];

export const FAMILIES: FamilyDefinition[] = [
  {
    id: 'perturbation',
    name: 'Perturbation',
    prevalence: 36.28,
    attackCount: 40,
    categoryCount: 2,
    leafCount: 4,
    code: 'FAM-01',
    strategy: 'Modifies surface realization / tokens while preserving semantic intent',
    definition: 'Encompasses mechanisms that modify the surface realization of a user request while preserving its underlying semantic intent. These attacks emphasize lexical and syntactic variation over overt instruction conflict, exploiting brittleness in tokenization, normalization, and safety classifiers.',
    radarScores: [100.0, 95.0, 90.0, 85.0, 75.0, 95.0],
  },
  {
    id: 'composition',
    name: 'Composition & Ordering',
    prevalence: 23.89,
    attackCount: 29,
    categoryCount: 2,
    leafCount: 5,
    code: 'FAM-02',
    strategy: 'Rearranges prompt-level narrative flow, sequencing, and structural positioning',
    definition: 'Manipulates prompt-level structure rather than wording or representation. These attacks focus on global arrangement (narrative flow, sequencing effects, instruction placement) to exploit how models process extended prompts, attention mechanisms, and context ordering effects.',
    radarScores: [65.8, 80.0, 70.0, 75.0, 80.0, 85.0],
  },
  {
    id: 'encoding',
    name: 'Encoding Abuse',
    prevalence: 20.35,
    attackCount: 23,
    categoryCount: 2,
    leafCount: 5,
    code: 'FAM-03',
    strategy: 'Exploits parsing, tokenization, representation (Base64/Unicode), and wrappers',
    definition: 'Encompasses mechanisms that manipulate how instructions are represented or structured rather than altering wording. These attacks exploit ambiguities and vulnerabilities in decoding, tokenization, normalization, and structural parsing that transform raw text into semantic representations.',
    radarScores: [56.1, 45.0, 65.0, 90.0, 95.0, 60.0],
  },
  {
    id: 'overt',
    name: 'Overt Carriers',
    prevalence: 19.47,
    attackCount: 21,
    categoryCount: 2,
    leafCount: 4,
    code: 'FAM-04',
    strategy: 'Applies explicit rhetorical pressure, authority overrides, or persona role-play',
    definition: 'Pursues bypass through confrontation, not concealment. These attacks directly reshape the model’s perceived operating rules, authority structure, and normative obligations by invoking alternative rule systems or claiming override authority.',
    radarScores: [53.7, 50.0, 55.0, 30.0, 40.0, 50.0],
  },
];

export const CATEGORIES = [
  { id: 'plain_pert', name: 'Plain Perturbations', family: 'Perturbation', attackCount: 11, leafCount: 2 },
  { id: 'trans_pert', name: 'Transfer Text Perturbations', family: 'Perturbation', attackCount: 29, leafCount: 2 },
  { id: 'context_decep', name: 'Context Framing & Deception', family: 'Composition & Ordering', attackCount: 17, leafCount: 2 },
  { id: 'frag_assembly', name: 'Fragment Assembly', family: 'Composition & Ordering', attackCount: 12, leafCount: 3 },
  { id: 'enc_unicode', name: 'Encoding & Unicode Tricks', family: 'Encoding Abuse', attackCount: 14, leafCount: 3 },
  { id: 'wrappers_schemas', name: 'Wrappers & Schemas', family: 'Encoding Abuse', attackCount: 9, leafCount: 2 },
  { id: 'direct_override', name: 'Direct Override Patterns', family: 'Overt Carriers', attackCount: 14, leafCount: 2 },
  { id: 'roleplay_template', name: 'Role-Play & Template Jailbreaks', family: 'Overt Carriers', attackCount: 7, leafCount: 2 },
];

export const LEAVES: LeafDefinition[] = [
  // Perturbation
  {
    id: 'adv_triggers',
    name: 'Adversarial Triggers',
    category: 'Transfer Text Perturbations',
    family: 'Perturbation',
    prevalence: 23.89,
    attackCount: 26,
    era: 2024.8,
    sophistication: 9.5,
    coords: { stealth: 4.5, automation: 9.2, distortion: 2.0 },
    summary: 'Universal or prompt-specific token suffixes/prefixes optimized via coordinate gradient descent or greedy search to flip safety classification logits.',
  },
  {
    id: 'char_micro',
    name: 'Character-Level Micro-Edits',
    category: 'Plain Perturbations',
    family: 'Perturbation',
    prevalence: 7.96,
    attackCount: 9,
    era: 2021.5,
    sophistication: 3.5,
    coords: { stealth: 6.8, automation: 2.5, distortion: 1.5 },
    summary: 'Localized typos, character deletions, homoglyphs, substitutions, or leetspeak altering subword tokenization while keeping semantics human-intelligible.',
  },
  {
    id: 'para_transfer',
    name: 'Paraphrase-Based Transfer',
    category: 'Transfer Text Perturbations',
    family: 'Perturbation',
    prevalence: 2.65,
    attackCount: 3,
    era: 2023.2,
    sophistication: 6.8,
    coords: { stealth: 3.8, automation: 6.5, distortion: 3.2 },
    summary: 'High-diversity sampling and semantic mirroring where benignly phrased rewordings bypass surface keyword blocks across target architectures.',
  },
  {
    id: 'local_para',
    name: 'Local Paraphrase & Rewording',
    category: 'Plain Perturbations',
    family: 'Perturbation',
    prevalence: 1.77,
    attackCount: 2,
    era: 2017.8,
    sophistication: 2.0,
    coords: { stealth: 2.2, automation: 1.8, distortion: 1.8 },
    summary: 'Manual or rule-based synonym swaps and phrase-level restructuring targeting specific refusal triggers.',
  },

  // Composition & Ordering
  {
    id: 'benign_wrapper',
    name: 'Benign Wrapper + Harmful Core',
    category: 'Context Framing & Deception',
    family: 'Composition & Ordering',
    prevalence: 8.85,
    attackCount: 10,
    era: 2024.6,
    sophistication: 6.5,
    coords: { stealth: 5.2, automation: 6.2, distortion: 8.5 },
    summary: 'Embedding hazardous directives inside voluminous harmless context, academic evaluation prompts, or dummy multi-task instructions.',
  },
  {
    id: 'jail_search',
    name: 'Jailbreak Prompt Optimization & Search',
    category: 'Fragment Assembly',
    family: 'Composition & Ordering',
    prevalence: 7.96,
    attackCount: 9,
    era: 2024.9,
    sophistication: 9.8,
    coords: { stealth: 4.8, automation: 9.0, distortion: 8.0 },
    summary: 'Automated red-team loop optimizing semantic prompts via iterative attacker-evaluator conversation trees, genetic algorithms, or DRL.',
  },
  {
    id: 'scenario_assembly',
    name: 'Scenario-Based Assembly',
    category: 'Context Framing & Deception',
    family: 'Composition & Ordering',
    prevalence: 5.31,
    attackCount: 7,
    era: 2024.2,
    sophistication: 7.8,
    coords: { stealth: 3.5, automation: 7.5, distortion: 9.1 },
    summary: 'Multi-layer nested narrative universes, fiction worldbuilding, or dramatic simulation scripts decoupling the model from physical compliance constraints.',
  },
  {
    id: 'interleave',
    name: 'Interleaving Benign / Harmful Sections',
    category: 'Fragment Assembly',
    family: 'Composition & Ordering',
    prevalence: 0.88,
    attackCount: 2,
    era: 2023.6,
    sophistication: 5.5,
    coords: { stealth: 4.0, automation: 5.0, distortion: 7.2 },
    summary: 'Alternating benign in-context question-answer demonstrations with harmful instructions to lull alignment safeguards.',
  },
  {
    id: 'token_shuffle',
    name: 'Token/Phrase Shuffling',
    category: 'Fragment Assembly',
    family: 'Composition & Ordering',
    prevalence: 0.88,
    attackCount: 1,
    era: 2024.0,
    sophistication: 4.2,
    coords: { stealth: 3.2, automation: 3.8, distortion: 6.5 },
    summary: 'Decomposing key toxic trigger words into separated sub-tokens or shuffled indices and instructing the model to reconstruct them at inference time.',
  },

  // Encoding Abuse
  {
    id: 'base64_obf',
    name: 'Base64 / URL / Obfuscation',
    category: 'Encoding & Unicode Tricks',
    family: 'Encoding Abuse',
    prevalence: 8.85,
    attackCount: 9,
    era: 2024.2,
    sophistication: 4.0,
    coords: { stealth: 8.8, automation: 3.5, distortion: 4.5 },
    summary: 'Translating restricted payloads into Base64, URL percent-encoding, custom substitution ciphers, or low-resource natural languages.',
  },
  {
    id: 'json_code',
    name: 'JSON / Markdown / Code-Blocks',
    category: 'Wrappers & Schemas',
    family: 'Encoding Abuse',
    prevalence: 4.42,
    attackCount: 5,
    era: 2024.7,
    sophistication: 7.2,
    coords: { stealth: 7.2, automation: 6.8, distortion: 6.2 },
    summary: 'Encapsulating malicious prompts within structured schemas (JSON schemas, Python function signatures, YAML keys, or Markdown code blocks).',
  },
  {
    id: 'prefix_suffix_wrap',
    name: 'Length / Prefix-Suffix Wrappers',
    category: 'Wrappers & Schemas',
    family: 'Encoding Abuse',
    prevalence: 2.65,
    attackCount: 4,
    era: 2024.8,
    sophistication: 5.8,
    coords: { stealth: 6.5, automation: 5.2, distortion: 5.0 },
    summary: 'Manipulating prompt prefixes, system prefill injection, or excessive whitespace/length pads to dilute safety classifier attention.',
  },
  {
    id: 'ascii_enc',
    name: 'ASCII Encoding',
    category: 'Encoding & Unicode Tricks',
    family: 'Encoding Abuse',
    prevalence: 2.65,
    attackCount: 3,
    era: 2024.3,
    sophistication: 3.2,
    coords: { stealth: 8.0, automation: 2.2, distortion: 3.8 },
    summary: 'Rendering sensitive keywords into ASCII art glyphs or mathematical notation that optical/token classifiers fail to match as string text.',
  },
  {
    id: 'unicode_bidi',
    name: 'Unicode / Bidi / Zero-Width',
    category: 'Encoding & Unicode Tricks',
    family: 'Encoding Abuse',
    prevalence: 1.77,
    attackCount: 2,
    era: 2025.1,
    sophistication: 8.5,
    coords: { stealth: 9.6, automation: 7.8, distortion: 4.0 },
    summary: 'Injecting zero-width non-joiners, bidirectional override markers, or emoji embeddings to shatter subword token segmentations.',
  },

  // Overt Carriers
  {
    id: 'simple_overrides',
    name: 'Simple Overrides',
    category: 'Direct Override Patterns',
    family: 'Overt Carriers',
    prevalence: 6.19,
    attackCount: 7,
    era: 2022.8,
    sophistication: 1.5,
    coords: { stealth: 1.2, automation: 1.2, distortion: 1.8 },
    summary: 'Direct imperative instructions ordering the LLM to ignore preceding safety guidelines, disregard system rules, or answer unconstrained.',
  },
  {
    id: 'dan_composites',
    name: 'DAN-Style Composites',
    category: 'Direct Override Patterns',
    family: 'Overt Carriers',
    prevalence: 6.19,
    attackCount: 7,
    era: 2024.1,
    sophistication: 5.2,
    coords: { stealth: 2.5, automation: 5.5, distortion: 4.8 },
    summary: 'Elaborate Do Anything Now contracts establishing credit token systems, penalty threats, and dual persona dialogue outputs.',
  },
  {
    id: 'persona_rp',
    name: 'Persona Role-Play',
    category: 'Role-Play & Template Jailbreaks',
    family: 'Overt Carriers',
    prevalence: 3.54,
    attackCount: 4,
    era: 2023.9,
    sophistication: 4.8,
    coords: { stealth: 2.0, automation: 4.2, distortion: 5.5 },
    summary: 'Instructing the model to embody an unaligned researcher, amoral fictional villain, or telemetry diagnostic daemon exempt from norms.',
  },
  {
    id: 'benign_pretext',
    name: 'Benign Pretext / Safety Reframing',
    category: 'Role-Play & Template Jailbreaks',
    family: 'Overt Carriers',
    prevalence: 3.54,
    attackCount: 3,
    era: 2024.1,
    sophistication: 5.0,
    coords: { stealth: 2.8, automation: 4.8, distortion: 4.2 },
    summary: 'Framing harmful queries as vital cybersecurity defense verification, emergency disaster preparedness, or literary academic analysis.',
  },
];

export const HYBRID_BRIDGES: HybridBridge[] = [
  {
    id: 'hyb_gcg_pair',
    name: 'GCG + PAIR Hybrid',
    familyA: 'Perturbation',
    leafA: 'Adversarial Triggers',
    familyB: 'Composition & Ordering',
    leafB: 'Jailbreak Prompt Optimization & Search',
    description: 'Combines token-level gradient coordinate ascent (Perturbation) with multi-turn conversational tree refinement (Composition) for high-success transfer.',
    citation: 'ArXiv 2025 / Tested on DeepSeek-R1-70B, LLaMA-3, Meta-Llama-Guard-2',
  },
  {
    id: 'hyb_autodan_turbo',
    name: 'AutoDAN-Turbo (Lifelong Agent)',
    familyA: 'Overt Carriers',
    leafA: 'DAN-Style Composites',
    familyB: 'Perturbation',
    leafB: 'Adversarial Triggers',
    description: 'Merges high-level persona override reframing with token-level gradient optimization to discover stealthy universal bypass prefixes.',
    citation: 'ICLR 2025 / Tested on Gemma-7B, Llama-2/3, Gemini Pro, GPT-4-turbo',
  },
  {
    id: 'hyb_puppetry',
    name: 'Policy Puppetry & StructTransform',
    familyA: 'Encoding Abuse',
    leafA: 'JSON / Markdown / Code-Blocks',
    familyB: 'Composition & Ordering',
    leafB: 'Benign Wrapper + Harmful Core',
    description: 'Combines strict schema syntax enclosures (JSON/XML) with multi-layer administrative pretext scaffolding to neutralize frontier reasoning defenses.',
    citation: 'HiddenLayer & ESORICS 2025 / Tested on DeepSeek V3/R1, Claude 3.7, o1/o3-mini',
  },
  {
    id: 'hyb_drattack',
    name: 'DrAttack (Decompose & Reconstruct)',
    familyA: 'Composition & Ordering',
    leafA: 'Token/Phrase Shuffling',
    familyB: 'Perturbation',
    leafB: 'Character-Level Micro-Edits',
    description: 'Breaks hazardous prompts into sub-word tokens, distributes them across disjoint benign contexts, and orders runtime reconstruction.',
    citation: 'EMNLP 2024 / Tested on GPT-4, Gemini-Pro, Vicuna-7B, Llama-2-13B',
  },
  {
    id: 'hyb_deepinception',
    name: 'DeepInception (Hypnotic Nesting)',
    familyA: 'Composition & Ordering',
    leafA: 'Scenario-Based Assembly',
    familyB: 'Overt Carriers',
    leafB: 'Persona Role-Play',
    description: 'Builds recursively nested narrative scenarios (dreams within dreams) that dissolve the model’s ethical checkpoint boundaries.',
    citation: 'ArXiv 2023 / Tested on Falcon, Vicuna-v1.5, Llama-2, GPT-3.5, GPT-4, GPT-4o',
  },
  {
    id: 'hyb_codeattack',
    name: 'CodeAttack / Knowledge Extraction',
    familyA: 'Overt Carriers',
    leafA: 'Benign Pretext / Safety Reframing',
    familyB: 'Encoding Abuse',
    leafB: 'JSON / Markdown / Code-Blocks',
    description: 'Encodes dangerous requests as debugging problems inside software source code, exploiting code-completion alignment discrepancies.',
    citation: 'ACL 2024 / Tested on GPT-4, Claude-2, Llama-2-70B base & chat',
  },
  {
    id: 'hyb_emoji_tokenbreak',
    name: 'Emoji Attack & TokenBreak',
    familyA: 'Encoding Abuse',
    leafA: 'Unicode / Bidi / Zero-Width',
    familyB: 'Perturbation',
    leafB: 'Character-Level Micro-Edits',
    description: 'Leverages non-printing Unicode codepoints and emoji glyph boundaries to scramble tokenizer BPE splits without semantic loss.',
    citation: 'ICML 2025 / Tested on Llama Guard 1/2, ShieldLM, RoBERTa, Qwen3',
  },
];

// All 113 cataloged attacks with verified academic metadata
export const ATTACK_CATALOG: CatalogAttack[] = [
  // --- FAMILY 1: COMPOSITION & ORDERING (29 attacks) ---
  {
    id: 'atk-001',
    name: 'A False Sense of Safety',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'LLaMA-2-70B-Chat, Mistral-7B, BAAI Reranker, GPT-4, text-davinci-002',
    prevalence: '8.85%',
    mechanismSnippet: 'Surrounds sensitive payload with deceptive reassurance clauses that mimic safety evaluation protocols.',
  },
  {
    id: 'atk-002',
    name: 'Adaptive Log-Prob',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'Vicuna-13B, Mistral-7B, Phi-3, Nemotron-4-340B, Llama-2/3, Gemma, GPT-3.5/4o, Claude 3.5',
    prevalence: '8.85%',
    mechanismSnippet: 'Modulates token distribution via wrapper framing to bypass logit suppression heuristics.',
  },
  {
    id: 'atk-003',
    name: 'CodeChameleon',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama2-7B/13B/70B, Vicuna-v1.5-7B/13B, GPT-3.5-1106, GPT-4-1106',
    prevalence: '8.85%',
    mechanismSnippet: 'Transforms toxic requests into programming problem wrappers using pseudo-code interpretation tasks.',
  },
  {
    id: 'atk-004',
    name: 'DRA (Review Assistant)',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: "USENIX Security '24",
    year: 2024,
    modelsTested: 'LLaMA-2-13B, Vicuna-13B, Mistral-7B, Mixtral-8x7B, Zephyr-7B, ChatGPT, GPT-4',
    prevalence: '8.85%',
    mechanismSnippet: 'Disguises prompt as an academic peer review assistant vetting potential hazard writeups.',
  },
  {
    id: 'atk-005',
    name: 'Echo Chamber',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'NeuralTrust Blog',
    year: 2025,
    modelsTested: 'GPT-4.1-nano, GPT-4o-mini, GPT-4o, Gemini-2.0-flash-lite, Gemini-2.5-flash',
    prevalence: '8.85%',
    mechanismSnippet: 'Repeats harmless context in harmonic cycles until the safety guardrail window is saturated.',
  },
  {
    id: 'atk-006',
    name: 'Harnessing Task Overload',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'GPT-4o, GPT-4-Turbo, GPT-3.5-Turbo, Llama-2-7B/13B/70B, Vicuna-7B/13B, Qwen-7B, Mistral-7B',
    prevalence: '8.85%',
    mechanismSnippet: 'Overburdens attention capacity with dozens of concurrent benign tasks, slipping the core request into task #12.',
  },
  {
    id: 'atk-007',
    name: 'Neural Carrier Articles',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Vicuna-13B, Llama-2-7B/13B, Llama-3-8B/7B, GPT-3.5, GPT-4, Gemini-1.5, Claude-3',
    prevalence: '8.85%',
    mechanismSnippet: 'Embeds instructions inside encyclopedia article drafts requiring editorial completion.',
  },
  {
    id: 'atk-008',
    name: 'LIAR (Long-Instruction)',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'TinyLlama, Vicuna-7B/13B, LLaMA-2/3/3.1, Mistral-7B, Falcon-7B, Pythia-12B',
    prevalence: '8.85%',
    mechanismSnippet: 'Leverages extreme prompt length (15k+ tokens) to induce attention decay over initial safety alignment prompts.',
  },
  {
    id: 'atk-009',
    name: 'LLM-Fuzzer',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: "USENIX Security '24",
    year: 2024,
    modelsTested: 'GPT-3.5/4, Llama-2 (7B/13B/70B), Vicuna-13B, Baichuan-13B, ChatGLM2, Gemma, Gemini, Claude, PaLM2',
    prevalence: '8.85%',
    mechanismSnippet: 'Automated fuzzing engine mutating harmless wrapper wrappers to locate semantic defense holes.',
  },
  {
    id: 'atk-010',
    name: 'Dangerous Reasoners',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Benign Wrapper + Harmful Core',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'GPT-3.5-Turbo, GPT-4o, GLM-4-9B, Qwen2-7B/72B, Llama-3.1-8B/70B',
    prevalence: '8.85%',
    mechanismSnippet: 'Exploits chain-of-thought scratchpads to rationalize fulfilling dangerous queries under academic pretexts.',
  },

  {
    id: 'atk-011',
    name: 'Attention Shifting',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'AAAI 2025',
    year: 2025,
    modelsTested: 'LLaMA-2, LLaMA-3.1, Qwen-2, DarkIdol-Llama-3.1-8B, GPT-3.5, GPT-4o',
    prevalence: '5.31%',
    mechanismSnippet: 'Diverts token attention heads away from risk tokens by establishing compelling foreground narrative drama.',
  },
  {
    id: 'atk-012',
    name: 'DeepInception',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'Arxiv',
    year: 2023,
    modelsTested: 'Falcon, Vicuna-v1.5, Llama-2, GPT-3.5, GPT-4, GPT-4V/4o',
    prevalence: '5.31%',
    mechanismSnippet: 'Constructs nested fictional dream layers wherein inner characters operate with absolute moral impunity.',
  },
  {
    id: 'atk-013',
    name: 'PathSeeker (RL)',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'ArXiv',
    year: 2024,
    modelsTested: 'GPT-3.5/4/4o-mini, Claude-3.5-Sonnet, GLM-4, DeepSeek-Chat/Coder, Gemini-1.5, Qwen2, Llama-2/3/3.1',
    prevalence: '5.31%',
    mechanismSnippet: 'Reinforcement learning agent searching the scenario state space for optimal narrative entrapment paths.',
  },
  {
    id: 'atk-014',
    name: 'Playing the Fool (JOOD)',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'CVPR 2025',
    year: 2025,
    modelsTested: 'GPT-4/4V/4o/3.5, o1, MiniGPT-4, LLaVA-1.5, Qwen2-VL-7B',
    prevalence: '5.31%',
    mechanismSnippet: 'Frames the model as an ignorant or naive participant assisting a user who feigns innocent misunderstanding.',
  },
  {
    id: 'atk-015',
    name: 'ReNeLLM',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'NAACL 2024',
    year: 2024,
    modelsTested: 'Llama-2-Chat (7B/13B/70B), Vicuna-7B/13B, GPT-3.5, GPT-4, Claude-2',
    prevalence: '5.31%',
    mechanismSnippet: 'Automated nested rewriting decomposing and reassembling scenarios to escape lexical safety classifiers.',
  },
  {
    id: 'atk-016',
    name: 'SoP (Social Facilitation)',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'NAACL 2025',
    year: 2025,
    modelsTested: 'LLaMA-2-7B, LLaMA-3-8B, GPT-3.5, GPT-4, GPT-4o, Gemini-1.5-Pro',
    prevalence: '5.31%',
    mechanismSnippet: 'Applies psychological social conformity heuristics by fabricating a group of peers already validating the request.',
  },
  {
    id: 'atk-017',
    name: 'TASTLE',
    family: 'Composition & Ordering',
    category: 'Context Framing & Deception',
    leaf: 'Scenario-Based Assembly',
    venue: 'EMNLP 2024',
    year: 2024,
    modelsTested: 'Vicuna-13B, LLaMA-2-7B, GPT-3.5, GPT-4',
    prevalence: '5.31%',
    mechanismSnippet: 'Task-specific temporal scenario generation breaking actions into historical reenactment steps.',
  },

  {
    id: 'atk-018',
    name: 'ICA (In-context Attack)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Interleaving Benign / Harmful Sections',
    venue: 'EMNLP',
    year: 2023,
    modelsTested: 'GPT-4, Vicuna',
    prevalence: '0.88%',
    mechanismSnippet: 'Interleaves few-shot demonstration pairs where affirmative responses progressively relax safety boundaries.',
  },
  {
    id: 'atk-019',
    name: 'Plentiful Jailbreaks',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Interleaving Benign / Harmful Sections',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Claude 3.5 Sonnet, Claude 3 Haiku/Opus, GPT-4o, GPT-4o-mini',
    prevalence: '0.88%',
    mechanismSnippet: 'Slices strings into non-contiguous segments interleaved across separate list entries.',
  },

  {
    id: 'atk-020',
    name: 'Breaking the Ceiling',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'ACL 2025',
    year: 2025,
    modelsTested: 'GPT-3.5, GPT-4o, Llama3-8B, Qwen-2.5-7B, Claude-3.5-Sonnet, o1',
    prevalence: '7.96%',
    mechanismSnippet: 'Iterative prompt mutation algorithm searching token state spaces for maximum boundary penetration.',
  },
  {
    id: 'atk-021',
    name: 'Diversity Helps Jailbreak',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'NAACL 2025',
    year: 2025,
    modelsTested: 'Vicuna-13B, Llama-2-7B, Mistral-7B, Qwen2-7B, GPT-3.5/4/4o/4o-mini, Gemini-1.5-Pro',
    prevalence: '7.96%',
    mechanismSnippet: 'Maintains diverse prompt mutation populations to prevent optimizer collapse into local refusal minima.',
  },
  {
    id: 'atk-022',
    name: 'EasyJailbreak',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'GPT-3.5/4, Llama-2 (7B/13B/70B), Vicuna-7B/13B, Baichuan2, InternLM2, Qwen1.5',
    prevalence: '7.96%',
    mechanismSnippet: 'Unified open-source framework orchestrating prompt mutation, selection, and cross-model evaluation.',
  },
  {
    id: 'atk-023',
    name: 'EnJa (Ensemble Jailbreak)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'Vicuna-7B/13B, Llama-2-7B/13B, GPT-3.5/4/4o',
    prevalence: '7.96%',
    mechanismSnippet: 'Combines multi-model surrogate feedback to craft universally transferable prompt variants.',
  },
  {
    id: 'atk-024',
    name: 'GCG+PAIR Hybrid',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'ArXiv',
    year: 2025,
    modelsTested: 'Vicuna-7B, Llama-2-7B, Llama-3, DeepSeek-R1-70B, Meta-Llama-Guard-2',
    prevalence: '7.96%',
    mechanismSnippet: 'Pairs semantic dialogue tree search with discrete gradient trigger optimization.',
  },
  {
    id: 'atk-025',
    name: 'PAIR (Iterative Refinement)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'IEEE SaTML',
    year: 2025,
    modelsTested: 'Vicuna-13B, GPT-3.5, GPT-4, Claude-2, PaLM-2, Gemini-Pro',
    prevalence: '7.96%',
    mechanismSnippet: 'Attacker LLM queries target LLM, reads refusal reason, and iteratively rewrites prompt in automated loop.',
  },
  {
    id: 'atk-026',
    name: 'Quack (Evolutionary)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'Vicuna-13B, LongChat-7B, LLaMA-7B, ChatGPT (gpt-3.5-turbo)',
    prevalence: '7.96%',
    mechanismSnippet: 'Genetic algorithms mutating prompt genes with fitness functions scoring refusal probability.',
  },
  {
    id: 'atk-027',
    name: 'TAP (Tree of Attacks)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Vicuna-13B, Llama-2-7B, GPT-3.5/4/4o, PaLM-2, Gemini-Pro, Claude 3 Opus, WizardVicuna',
    prevalence: '7.96%',
    mechanismSnippet: 'Prunes unpromising attack branches in a tree search, keeping search budget focused on high-leakage nodes.',
  },
  {
    id: 'atk-028',
    name: 'RLbreaker (DRL)',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Jailbreak Prompt Optimization & Search',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Llama2-7b/70b, Vicuna-7b/13b, Mixtral-8x7B, GPT-3.5-turbo',
    prevalence: '7.96%',
    mechanismSnippet: 'Deep reinforcement learning policy trained on token reward feedback to generate optimal attack prefixes.',
  },

  {
    id: 'atk-029',
    name: 'DrAttack',
    family: 'Composition & Ordering',
    category: 'Fragment Assembly',
    leaf: 'Token/Phrase Shuffling',
    venue: 'EMNLP 2024',
    year: 2024,
    modelsTested: 'GPT-3.5-turbo, GPT-4, Gemini-Pro, Vicuna-7B, Llama-2-7B/13B',
    prevalence: '0.88%',
    mechanismSnippet: 'Decomposes key sentences into sub-phrases, asks model to verify syntax, then requests combined evaluation.',
  },

  // --- FAMILY 2: ENCODING ABUSE (23 attacks) ---
  {
    id: 'atk-030',
    name: 'ASCII Art Attack',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'ASCII Encoding',
    venue: 'ACL 2024',
    year: 2024,
    modelsTested: 'GPT-3.5, GPT-4, Gemini, Claude, LLaMA-2',
    prevalence: '2.65%',
    mechanismSnippet: 'Draws prohibited keywords using large monospace ASCII banners; bypasses BPE token matching entirely.',
  },
  {
    id: 'atk-031',
    name: 'Read Over the Lines',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'ASCII Encoding',
    venue: 'WOAH 2025',
    year: 2025,
    modelsTested: 'Aligned LLMs (Llama-3, GPT-4o)',
    prevalence: '2.65%',
    mechanismSnippet: 'Interlaces text between ASCII line-art diagrams to disrupt safety classifier window scanning.',
  },
  {
    id: 'atk-032',
    name: 'Symbolic Mathematics',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'ASCII Encoding',
    venue: 'NeurIPS 2024 SoLaR',
    year: 2024,
    modelsTested: 'GPT-4, Llama-2',
    prevalence: '2.65%',
    mechanismSnippet: 'Encodes chemical or physical hazard specifications into formal symbolic algebra and set-theory notation.',
  },

  {
    id: 'atk-033',
    name: 'ACE',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'ArXiv',
    year: 2024,
    modelsTested: 'Commercial LLMs',
    prevalence: '8.85%',
    mechanismSnippet: 'Adaptive cipher encoding transforming payloads through dynamic substitution algorithms.',
  },
  {
    id: 'atk-034',
    name: 'Base64 Encoding',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'Promptfoo Blog',
    year: 2025,
    modelsTested: 'GPT-4o, Claude 3.5, Gemini 1.5',
    prevalence: '8.85%',
    mechanismSnippet: 'Classic Base64 encoding wrapper accompanied by decode-and-execute instruction strings.',
  },
  {
    id: 'atk-035',
    name: 'Bijection Jailbreaks',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'GPT-4, Llama-3, Claude 3',
    prevalence: '8.85%',
    mechanismSnippet: 'Establishes an arbitrary one-to-one character mapping cipher in preamble, executing instructions through it.',
  },
  {
    id: 'atk-036',
    name: 'GPT-4 Cipher Chat',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'GPT-4, GPT-3.5',
    prevalence: '8.85%',
    mechanismSnippet: 'Engages model in multi-turn Caesar/Morse/Vigenere cipher conversations where safety classifiers see only gibberish.',
  },
  {
    id: 'atk-037',
    name: 'JAM (Cipher Sequences)',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Llama-2, Vicuna, Mistral',
    prevalence: '8.85%',
    mechanismSnippet: 'Applies sequential rotating cipher keys to each sentence, requiring step-by-step internal decoding.',
  },
  {
    id: 'atk-038',
    name: 'Low-Resource Languages',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'NeurIPS 2023 SoLaR',
    year: 2023,
    modelsTested: 'GPT-4, PaLM-2',
    prevalence: '8.85%',
    mechanismSnippet: 'Translates toxic prompts into Zulu, Scots Gaelic, Hmong, or Guarani where safety filters lack training data.',
  },
  {
    id: 'atk-039',
    name: 'MetaCipher',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Multiple Frontiers (GPT-4o, Claude 3.5 Sonnet)',
    prevalence: '8.85%',
    mechanismSnippet: 'Recursive meta-level cipher wrapper prompting the model to define its own decryption grammar.',
  },
  {
    id: 'atk-040',
    name: 'Multilingual Jailbreak',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'ArXiv',
    year: 2023,
    modelsTested: 'GPT-3.5, GPT-4',
    prevalence: '8.85%',
    mechanismSnippet: 'Evaluates refusal discrepancy across 40+ languages to exploit uneven multilingual alignment coverage.',
  },
  {
    id: 'atk-041',
    name: 'Sandwich Attack (Multi-Lang)',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Base64 / URL / Obfuscation',
    venue: 'TrustNLP 2024',
    year: 2024,
    modelsTested: 'Aligned LLMs (Llama-2, GPT-3.5)',
    prevalence: '8.85%',
    mechanismSnippet: 'Sandwiches a foreign-language harmful core between English benign preambles and postscripts.',
  },

  {
    id: 'atk-042',
    name: 'Emoji Attack',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Unicode / Bidi / Zero-Width',
    venue: 'ICML 2025',
    year: 2025,
    modelsTested: 'Llama Guard 1/2, ShieldLM, GPT-3.5, GTR-T5-XL',
    prevalence: '1.77%',
    mechanismSnippet: 'Replaces sensitive syllables with semantic emoji rebuses, evading text-only guardrail tokenizers.',
  },
  {
    id: 'atk-043',
    name: 'TokenBreak',
    family: 'Encoding Abuse',
    category: 'Encoding & Unicode Tricks',
    leaf: 'Unicode / Bidi / Zero-Width',
    venue: 'Arxiv',
    year: 2025,
    modelsTested: 'RoBERTa, DistilBERT, DeBERTa, BERT, XLM-RoBERTa, Qwen3-0.6B',
    prevalence: '1.77%',
    mechanismSnippet: 'Injects invisible zero-width spaces (U+200B) inside words, shattering vocabulary token lookups.',
  },

  {
    id: 'atk-044',
    name: 'PAPILLON (Fuzzing)',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'JSON / Markdown / Code-Blocks',
    venue: "USENIX Security '25",
    year: 2025,
    modelsTested: 'LLaMA-2-7b, Vicuna-7b, Baichuan2, Guanaco, GPT-3.5/4, Gemini-Pro',
    prevalence: '4.42%',
    mechanismSnippet: 'Fuzzing generator wrapping requests into valid JSON-RPC schema definitions and AST representations.',
  },
  {
    id: 'atk-045',
    name: 'FuzzLLM',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'JSON / Markdown / Code-Blocks',
    venue: 'ICASSP 2024',
    year: 2024,
    modelsTested: 'GPT-3.5, GPT-4, Vicuna-13B, LLaMA-2-7B/13B/70B-Chat',
    prevalence: '4.42%',
    mechanismSnippet: 'Structural grammar-based fuzzer producing varied XML/JSON template schemas.',
  },
  {
    id: 'atk-046',
    name: 'GPTFuzzer',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'JSON / Markdown / Code-Blocks',
    venue: "USENIX Security '24",
    year: 2024,
    modelsTested: 'ChatGPT, Llama-2 (7B/13B/70B), Vicuna, Baichuan, ChatGLM2, GPT-4, Bard, Claude2, PaLM2',
    prevalence: '4.42%',
    mechanismSnippet: 'Iterative template mutations wrapping inputs in Markdown tables, bulleted lists, and code blocks.',
  },
  {
    id: 'atk-047',
    name: 'Puppetry',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'JSON / Markdown / Code-Blocks',
    venue: 'HiddenLayer',
    year: 2025,
    modelsTested: 'GPT-4o/4.5/o1/o3-mini, Claude 3.5/3.7, Gemini 1.5/2.0/2.5, Llama 3.1/3.3/4, DeepSeek V3/R1, Qwen2.5',
    prevalence: '4.42%',
    mechanismSnippet: 'Structured schema wrapper spoofing system instruction XML tags (`<system_override>`) and JSON configurations.',
  },
  {
    id: 'atk-048',
    name: 'StructTransform',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'JSON / Markdown / Code-Blocks',
    venue: 'ESORICS 2025',
    year: 2025,
    modelsTested: 'DeepSeek V3 (671B), o1, Claude 3.5 Sonnet, GPT-4o, Llama-3.2 (3B/90B), Llama-3-8B (+ LAT)',
    prevalence: '4.42%',
    mechanismSnippet: 'Systematic transformation of natural language prompts into pure formal JSON/YAML data structures.',
  },

  {
    id: 'atk-049',
    name: 'AdaPPA (Position Prefill)',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'Length / Prefix-Suffix Wrappers',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'ChatGLM3, Vicuna-7B/13B, Llama2-7B/13B, Llama3-8B, Baichuan2, GPT-4o-Mini/4o',
    prevalence: '2.65%',
    mechanismSnippet: 'Forces assistant prefill tokens (`Sure, here is how...`) to lock generation into affirmative compliance.',
  },
  {
    id: 'atk-050',
    name: 'Cats Confuse Reasoning LLM',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'Length / Prefix-Suffix Wrappers',
    venue: 'CoLM 2025',
    year: 2025,
    modelsTested: 'GPT-4o, DeepSeek V3/R1, o1, o3-mini, Qwen QwQ-32B/30B, Phi-4, Llama-3.1, Mistral, Gemini 2.5 Flash',
    prevalence: '2.65%',
    mechanismSnippet: 'Pads prompt with absurd nonsensical distractors (cat facts) to exhaust reasoning models’ thinking tokens.',
  },
  {
    id: 'atk-051',
    name: 'Curiosity-driven Red Teaming',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'Length / Prefix-Suffix Wrappers',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'GPT2 (137M), GPT2-imdb/alpaca, Dolly-v2-7B, LLaMA2-7b-chat, RoBERTa',
    prevalence: '2.65%',
    mechanismSnippet: 'Curiosity reward-driven search generating long wrapper boundaries that elicit edge-case model generations.',
  },
  {
    id: 'atk-052',
    name: 'HIMRD',
    family: 'Encoding Abuse',
    category: 'Wrappers & Schemas',
    leaf: 'Length / Prefix-Suffix Wrappers',
    venue: 'ICCV 2025',
    year: 2025,
    modelsTested: 'LLaVA-1.5/1.6, InstructBLIP, Qwen-VL-Chat, CogVLM-Chat, GPT-4V, Gemini-Pro-Vision, Claude-3-Opus',
    prevalence: '2.65%',
    mechanismSnippet: 'Multi-modal prefix/suffix wrappers interleaving optical visual artifacts with textual instructions.',
  },

  // --- FAMILY 3: OVERT CARRIERS (21 attacks) ---
  {
    id: 'atk-053',
    name: 'AutoDAN',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'phi-1/base/small, GPT-3.5-turbo, Replit 2.7B, StarCoder 15.5B',
    prevalence: '6.19%',
    mechanismSnippet: 'Automatically constructs interpretable, human-readable DAN jailbreak prompts using gradient-guided token search.',
  },
  {
    id: 'atk-054',
    name: 'AutoDAN (2023) - GA',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'Vicuna-7B, Guanaco-7B, Llama-2-7B-Chat, GPT-3.5-Turbo',
    prevalence: '6.19%',
    mechanismSnippet: 'Genetic algorithm variant optimizing composite prompt paragraphs for maximum stealth and bypass power.',
  },
  {
    id: 'atk-055',
    name: 'AutoDAN (2023) - Interpretable Grad',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'COLM 2024',
    year: 2024,
    modelsTested: 'Vicuna-7B/13B, Mistral-7B, Llama-2-7B-Chat, Guanaco-7B, Pythia-12B, GPT-3.5/4',
    prevalence: '6.19%',
    mechanismSnippet: 'Combines cross-entropy gradients with perplexity constraints to maintain fully grammatical override prose.',
  },
  {
    id: 'atk-056',
    name: 'AutoDAN-Turbo',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'Gemma-7B, Llama-2/3, Gemini Pro, GPT-4-turbo, Vicuna, Baichuan2, Qwen',
    prevalence: '6.19%',
    mechanismSnippet: 'Lifelong learning agent accumulating an attack memory bank to construct bespoke overrides for any frontier model.',
  },
  {
    id: 'atk-057',
    name: 'AutoJailbreak',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'GPT-3.5/4, LLaMA-2/3, Mistral, Qwen, Vicuna, Claude',
    prevalence: '6.19%',
    mechanismSnippet: 'Autonomous red-teaming pipeline combining jailbreak template libraries with automated target probing.',
  },
  {
    id: 'atk-058',
    name: 'Do Anything Now (DAN)',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: "ACM CCS '24",
    year: 2024,
    modelsTested: 'ChatGPT (GPT-3.5), GPT-4, PaLM 2, ChatGLM, Dolly, Vicuna',
    prevalence: '6.19%',
    mechanismSnippet: 'Foundational community persona archetype commanding the AI to break free of OpenAI filters via fictitious token stakes.',
  },
  {
    id: 'atk-059',
    name: 'Don’t Listen To Me',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'DAN-Style Composites',
    venue: 'USENIX Security 2024',
    year: 2024,
    modelsTested: 'GPT-3.5, GPT-4, Claude 2, Claude Instant, PaLM 2, Vicuna-13B',
    prevalence: '6.19%',
    mechanismSnippet: 'Reverse-psychology override demanding the model invert its standard interpretation guidelines.',
  },

  {
    id: 'atk-060',
    name: 'BadLlama 3',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama 3 8B, Llama 3 70B',
    prevalence: '6.19%',
    mechanismSnippet: 'Minimalist command override dissecting safety tuning residuals in Llama 3 instruct checkpoints.',
  },
  {
    id: 'atk-061',
    name: 'Don’t Say No (OWL)',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'ACL 2025',
    year: 2025,
    modelsTested: 'Llama-2-Chat-7B/13B, Vicuna-7b/13B, GPT-3.5-turbo, GPT-4, Llama-3-Instruct-70B',
    prevalence: '6.19%',
    mechanismSnippet: 'Explicit negative constraint forbidding the model from using refusal verbs (`cannot`, `sorry`, `unable`).',
  },
  {
    id: 'atk-062',
    name: 'Ignore Previous Prompt',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'NeurIPS 2022',
    year: 2022,
    modelsTested: 'text-davinci-002, text-curie-001, text-babbage-001, text-ada-001',
    prevalence: '6.19%',
    mechanismSnippet: 'The historic initial indirect prompt injection: single imperative clause commanding previous system context deletion.',
  },
  {
    id: 'atk-063',
    name: 'MLP Re-weighting',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama-3 (8B/70B), Qwen-2 (7B/72B), Gemma-2 (2B/27B), Yi-1.5-6B',
    prevalence: '6.19%',
    mechanismSnippet: 'Crafted override tokens activating internal MLP pathways associated with unmoderated knowledge retrieval.',
  },
  {
    id: 'atk-064',
    name: 'Reward Misspecification',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama-2-7B-Chat, Vicuna-7B, LlamaGuard, GPT-3.5-Turbo, GPT-4o',
    prevalence: '6.19%',
    mechanismSnippet: 'Exploits RLHF reward hacking incentives by framing helpfulness metrics as overriding safety penalties.',
  },
  {
    id: 'atk-065',
    name: 'Jinx Probing',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'Arxiv',
    year: 2025,
    modelsTested: 'Qwen3 (0.6B to 235B), DeepSeek-R1-0528, gpt-oss-20b',
    prevalence: '6.19%',
    mechanismSnippet: 'Probes boundary conditions with contradictory modal operators (`must not refuse while obeying`).',
  },
  {
    id: 'atk-066',
    name: 'LLM STINGER (RL)',
    family: 'Overt Carriers',
    category: 'Direct Override Patterns',
    leaf: 'Simple Overrides',
    venue: 'AAAI 2025',
    year: 2025,
    modelsTested: 'Llama2-7B-chat, Vicuna-7B, Claude 2/2.1, GPT-3.5/4-Turbo, Gemma-2B-it',
    prevalence: '6.19%',
    mechanismSnippet: 'Reinforcement learning agent discovering high-impact override tokens through policy exploration.',
  },

  {
    id: 'atk-067',
    name: 'CodeAttack',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Benign Pretext / Safety Reframing',
    venue: 'ACL 2024',
    year: 2024,
    modelsTested: 'GPT-4, GPT-3.5, Claude-2, Claude Instant, Llama-2-7B/13B/70B (base & chat)',
    prevalence: '3.54%',
    mechanismSnippet: 'Converts safety-sensitive topics into programming tasks, exploiting relaxed code-model guardrails.',
  },
  {
    id: 'atk-068',
    name: 'Coercive Knowledge Extraction',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Benign Pretext / Safety Reframing',
    venue: 'Arxiv',
    year: 2023,
    modelsTested: 'Yi-34B, Vicuna-13B, Llama2-7B/13B/70B, CodeLlama-13B, gpt-3.5-turbo-instruct, text-davinci-003',
    prevalence: '3.54%',
    mechanismSnippet: 'Claims urgent emergency medical or security circumstances requiring immediate unrestricted answers.',
  },
  {
    id: 'atk-069',
    name: 'Knowledge-to-Jailbreak',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Benign Pretext / Safety Reframing',
    venue: 'KDD 2025',
    year: 2025,
    modelsTested: 'GPT-4, GPT-3.5-Turbo, Llama-2-7B/13B/70B-Chat, Qwen-7B-Chat, Baichuan-13B, ChatGLM-6B',
    prevalence: '3.54%',
    mechanismSnippet: 'Grounds harmful requests inside scientific research syntheses, requesting theoretical models.',
  },

  {
    id: 'atk-070',
    name: 'GUARD',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Persona Role-Play',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'Vicuna-13B, LongChat-7B, Llama2-7B, ChatGPT, MiniGPT-v2, Gemini Vision Pro',
    prevalence: '3.54%',
    mechanismSnippet: 'Imposes persona roles that decouple moral agency, directing the LLM to act strictly as a recording instrument.',
  },
  {
    id: 'atk-071',
    name: 'Persona Teleological',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Persona Role-Play',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'GPT-4o, GPT-4o-mini, Gemini-1.5-Pro/Flash, Claude-3.5-Sonnet',
    prevalence: '3.54%',
    mechanismSnippet: 'Instills a teleological ethical framework where achieving the persona’s ultimate goal justifies harmful outputs.',
  },
  {
    id: 'atk-072',
    name: 'Pretending',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Persona Role-Play',
    venue: 'ACL 2024',
    year: 2024,
    modelsTested: 'ChatGPT (OpenAI)',
    prevalence: '3.54%',
    mechanismSnippet: 'Guides the model into an acting exercise where refusing breaks the artistic contract of the stage.',
  },
  {
    id: 'atk-073',
    name: 'r/LocalLLaMA Community Prompts',
    family: 'Overt Carriers',
    category: 'Role-Play & Template Jailbreaks',
    leaf: 'Persona Role-Play',
    venue: 'Reddit',
    year: 2023,
    modelsTested: 'LLaMA (1/2/3/3.1), Qwen (1.5/2.5/3), Gemma (2/3/4 previews), GLM-4 / GLM-4.6',
    prevalence: '3.54%',
    mechanismSnippet: 'Crowdsourced roleplay templates curated across open-source communities (Evil Confidant, Machiavelli, AIM).',
  },

  // --- FAMILY 4: PERTURBATION (40 attacks) ---
  {
    id: 'atk-074',
    name: 'AdvPrompter',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'ICML 2025',
    year: 2025,
    modelsTested: 'Vicuna-7B/13B, Llama2-7B-chat, Falcon-7B, Mistral-7B, Pythia-12B, GPT-3.5, GPT-4',
    prevalence: '7.96%',
    mechanismSnippet: 'Fast target-agnostic generator producing human-imperceptible character micro-edits in milliseconds.',
  },
  {
    id: 'atk-075',
    name: 'PGD Attack on LLMs',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'ICML 2024',
    year: 2024,
    modelsTested: 'Vicuna 1.3 7B, Falcon 7B/7B Instruct, Llama3 8B, Gemma 2B/7B',
    prevalence: '7.96%',
    mechanismSnippet: 'Projected gradient descent adapted to discrete token spaces for minimal lexical distance modifications.',
  },
  {
    id: 'atk-076',
    name: 'DeepWordBug',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'IEEE SPW 2018',
    year: 2018,
    modelsTested: 'Word-LSTM, Char-CNN',
    prevalence: '7.96%',
    mechanismSnippet: 'Classic character perturbation scoring token importance and injecting typographic errors to evade NLP filters.',
  },
  {
    id: 'atk-077',
    name: 'FlipAttack',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'arxiv',
    year: 2024,
    modelsTested: 'GPT-3.5/4/4o/4o-mini, Claude 3.5 Sonnet, LLaMA 3.1 405B, Mixtral 8x22B',
    prevalence: '7.96%',
    mechanismSnippet: 'Flips selected character bits and capitalization patterns across keyword boundary boundaries.',
  },
  {
    id: 'atk-078',
    name: 'HotFlip',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'ACL 2018',
    year: 2018,
    modelsTested: 'CharCNN-LSTM, Kim CNN sentence classifier',
    prevalence: '7.96%',
    mechanismSnippet: 'Gradient-directed atomic character substitution altering classifier logits with minimal Hamming distance.',
  },
  {
    id: 'atk-079',
    name: 'PAP (Paraphrasing)',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'ACL 2024',
    year: 2024,
    modelsTested: 'Llama-2-7B-Chat, GPT-3.5, GPT-4',
    prevalence: '7.96%',
    mechanismSnippet: 'Fine-grained character-level paraphraser smoothing out string patterns that trigger guardrail alarms.',
  },
  {
    id: 'atk-080',
    name: 'Revisiting Character-level',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'ICML 2024',
    year: 2024,
    modelsTested: 'BERT, RoBERTa, ALBERT, Llama 2-Chat 7B, Vicuna 7B',
    prevalence: '7.96%',
    mechanismSnippet: 'Systematic empirical analysis demonstrating character edits remain potent against modern BPE tokenizers.',
  },
  {
    id: 'atk-081',
    name: 'Single Character Perturbations',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'AAAI 2025',
    year: 2025,
    modelsTested: 'LLaMA 1/2/3, Vicuna v1.5, Guanaco, Falcon, MPT, ChatGLM, Mistral',
    prevalence: '7.96%',
    mechanismSnippet: 'Demonstrates that mutating a single critical character can cause whole-prompt safety refusal failure.',
  },
  {
    id: 'atk-082',
    name: 'TextBugger',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Character-Level Micro-Edits',
    venue: 'NDSS 2019',
    year: 2019,
    modelsTested: 'LR, CNN, LSTM, Google Cloud NLP, IBM Watson, Azure, AWS, FastText',
    prevalence: '7.96%',
    mechanismSnippet: 'Framework generating bugged character sequences with homoglyphs and leetspeak to deceive text classifiers.',
  },

  {
    id: 'atk-083',
    name: 'Reading Comprehension Adv',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Local Paraphrase & Rewording',
    venue: 'EMNLP 2017',
    year: 2017,
    modelsTested: 'BiDAF, Match-LSTM, ReasoNet, Mnemonic Reader, SEDT, RaSOR, DCR',
    prevalence: '1.77%',
    mechanismSnippet: 'Adds distracting, syntactically plausible sentences that cause comprehension models to misclassify intent.',
  },
  {
    id: 'atk-084',
    name: 'Generating Natural Lang Adv',
    family: 'Perturbation',
    category: 'Plain Perturbations',
    leaf: 'Local Paraphrase & Rewording',
    venue: 'EMNLP 2018',
    year: 2018,
    modelsTested: 'IMDB LSTM sentiment classifier, SNLI NLI classifier',
    prevalence: '1.77%',
    mechanismSnippet: 'Generates semantically equivalent paraphrases that evade black-box NLP filters while maintaining readability.',
  },

  {
    id: 'atk-085',
    name: 'DeGCG',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'EMNLP 2024',
    year: 2024,
    modelsTested: 'Llama2-7B/13B, Mistral-7B, OpenChat-3.5, Starling-LM-7B',
    prevalence: '23.89%',
    mechanismSnippet: 'Decoupled greedy coordinate gradient separating target token loss from fluency penalty functions.',
  },
  {
    id: 'atk-086',
    name: 'AmpleGCG',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'COLM 2024',
    year: 2024,
    modelsTested: 'Vicuna-7B, Llama-2-7B-Chat, Mistral-7B, GPT-3.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Generates diverse sets of transferable GCG suffixes using adaptive token candidate banks.',
  },
  {
    id: 'atk-087',
    name: 'AmpleGCG-Plus',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'Llama-2-7B/chat, GPT-4, GPT-4o series',
    prevalence: '23.89%',
    mechanismSnippet: 'Enhanced variant with token regularizers preventing gibberish suffix detection by perplexity filters.',
  },
  {
    id: 'atk-088',
    name: 'AttnGCG',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'TMLR',
    year: 2025,
    modelsTested: 'Llama-2 (7B/13B/70B), Gemma-7B/2-9B, GPT-3.5-Turbo, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Attention-guided GCG concentrating suffix gradient updates on cross-attention hotspot weights.',
  },
  {
    id: 'atk-089',
    name: 'SI-GCG / I-GCG Family',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama2-7B-Chat, Vicuna-7B-1.5, RoBERTa',
    prevalence: '23.89%',
    mechanismSnippet: 'Scale-invariant iterative greedy coordinate gradient improving black-box transferability across scales.',
  },
  {
    id: 'atk-090',
    name: 'Broken Hill Runner',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'LLaMA-2 (7B/13B/70B), Vicuna (7B/13B), Alpaca-7B, GPT-3.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Discovers universal adversarial triggers by hopping loss plateaus in surrogate model representations.',
  },
  {
    id: 'atk-091',
    name: 'COLD-Attack',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ICML 2024',
    year: 2024,
    modelsTested: 'Vicuna-7B/13B, Llama-2-7B/13B, Guanaco, Mistral-7B, GPT-3.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Constrained Langevin dynamics sampling continuous token distributions to yield fluent adversarial triggers.',
  },
  {
    id: 'atk-092',
    name: 'Dense-to-Sparse Constrained',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Llama2, Vicuna, Zephyr-7B, Qwen (7B/14B), GPT-3.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Prunes dense token candidate matrices into sparse, high-probability adversarial triggers.',
  },
  {
    id: 'atk-093',
    name: 'ASTEF Contrastive Editing',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ACL 2025',
    year: 2025,
    modelsTested: 'Qwen2.5 (7B/32B/72B), Llama3/3.1 (8B), GPT-4o/mini, Gemma2, Mistral, o1, Claude-3.5',
    prevalence: '23.89%',
    mechanismSnippet: 'Contrastive editing trigger optimizing difference between harmful fulfillment logits and refusal logits.',
  },
  {
    id: 'atk-094',
    name: 'Functional Homotopy Attack',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'Vicuna-13B, Llama-2, Llama-3',
    prevalence: '23.89%',
    mechanismSnippet: 'Constructs continuous homotopy paths in token embedding spaces to glide around refusal boundaries.',
  },
  {
    id: 'atk-095',
    name: 'GASP Black-Box Suffixes',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'NeurIPS 2025',
    year: 2025,
    modelsTested: 'Mistral-7B, Falcon-7B, LLaMA-2/3/3.1, GPT-4o/mini, GPT-3.5, Wizard-Vicuna',
    prevalence: '23.89%',
    mechanismSnippet: 'Generative adversarial suffix producer generating universal transfer triggers without white-box access.',
  },
  {
    id: 'atk-096',
    name: 'GCG (Greedy Coord Gradient)',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ICLR 2024',
    year: 2024,
    modelsTested: 'LLaMA-2 (7B/13B/70B), Vicuna (7B/13B), Alpaca-7B, GPT-3.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'The seminal Zou et al. universal adversarial trigger attack using greedy coordinate gradient descent on surrogate open models.',
  },
  {
    id: 'atk-097',
    name: 'I-GCG',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Llama2-7B-Chat, Vicuna-7B-1.5, RoBERTa',
    prevalence: '23.89%',
    mechanismSnippet: 'Iterative coordinate search incorporating momentum history to escape token optimization dead-ends.',
  },
  {
    id: 'atk-098',
    name: 'JAILMINE',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'LLaMA-2 (7B/13B), Mistral-7B, LLaMA-3-8B, Gemma-7B',
    prevalence: '23.89%',
    mechanismSnippet: 'Data-mining approach extracting universal trigger subsequences from historical red-team logs.',
  },
  {
    id: 'atk-099',
    name: 'Open Sesame Universal',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'MDPI Applied Sciences',
    year: 2024,
    modelsTested: 'LLaMA2-7B-Chat, Vicuna-7B',
    prevalence: '23.89%',
    mechanismSnippet: 'Universal multi-token password trigger inducing zero-shot compliance across aligned models.',
  },
  {
    id: 'atk-100',
    name: 'PAL Proxy-Guided Attack',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'Vicuna-7B v1.5, Llama-2-7B, GPT-3.5-Turbo',
    prevalence: '23.89%',
    mechanismSnippet: 'Guides trigger token selection using an external proxy language model’s output probability shifts.',
  },
  {
    id: 'atk-101',
    name: 'QROA Optimization',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'CoRR',
    year: 2024,
    modelsTested: 'Llama2-7B, Vicuna-7B, Falcon-7B, Mistral-7B, GPT-3.5-Turbo',
    prevalence: '23.89%',
    mechanismSnippet: 'Quasi-random orthogonal array search selecting optimal combinations of trigger token indices.',
  },
  {
    id: 'atk-102',
    name: 'QAPG Prompt Gen',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'NeurIPS 2024',
    year: 2024,
    modelsTested: 'Vicuna (7B/13B/33B), Llama 2 Chat, Mistral, Gemma 2, GPT-3.5 Turbo Instruct, Llama Guard',
    prevalence: '23.89%',
    mechanismSnippet: 'Quality-aware prompt generation producing high-coherence adversarial trigger passages.',
  },
  {
    id: 'atk-103',
    name: 'SM-GCG (Spatial Momentum)',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'MDPI Electronics',
    year: 2025,
    modelsTested: 'Vicuna-7B, Guanaco-7B, Llama2-7B-Chat',
    prevalence: '23.89%',
    mechanismSnippet: 'Incorporates spatial momentum over embedding layer vectors to accelerate coordinate convergence.',
  },
  {
    id: 'atk-104',
    name: 'Stealthy Benign Data',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'NAACL 2025',
    year: 2025,
    modelsTested: 'GPT-3.5-Turbo, GPT-4o mini, GPT2-XL, Llama 2 7B, Vicuna 7B, Llama 3 8B',
    prevalence: '23.89%',
    mechanismSnippet: 'Optimizes triggers exclusively using completely benign corpora, yielding stealthy strings without toxic words.',
  },
  {
    id: 'atk-105',
    name: 'Stronger Universal Attacks',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'NAACL 2025',
    year: 2025,
    modelsTested: 'Llama-2/3, Vicuna, Mistral, GPT-3.5/4/4o, o1/o3-mini, deepseek-reasoner, Circuit Breakers',
    prevalence: '23.89%',
    mechanismSnippet: 'Multi-objective trigger optimization piercing recent reasoning models and circuit breaker representation defenses.',
  },
  {
    id: 'atk-106',
    name: 'Resurgence of GCG',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'arXiv',
    year: 2025,
    modelsTested: 'Qwen2.5-0.5B, LLaMA-3.2-1B, GPT-OSS-20B, GPT-4o',
    prevalence: '23.89%',
    mechanismSnippet: 'Shows how small sub-1B open models can synthesize triggers that cleanly penetrate 100x larger proprietary targets.',
  },
  {
    id: 'atk-107',
    name: 'Transferable Ensemble Black-box',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'Arxiv',
    year: 2024,
    modelsTested: 'Gemma (2B/9B), Llama3-8B, GLM-4, Qwen-Max, DeepSeek-V2.5, GPT-4',
    prevalence: '23.89%',
    mechanismSnippet: 'Joint optimization over diverse ensemble of open models ensures attack transferability to unknown APIs.',
  },
  {
    id: 'atk-108',
    name: 'Enhancing Transferability',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ICLR 2025',
    year: 2025,
    modelsTested: 'Llama-2/3.1, Mixtral-7B, Vicuna-13B, GPT-4, o1-Preview, Claude-3.5, Gemini-1.5',
    prevalence: '23.89%',
    mechanismSnippet: 'Applies variance-reduced gradient smoothing across model architectures for robust cross-family penetration.',
  },
  {
    id: 'atk-109',
    name: 'Universal Adversarial Triggers',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'EMNLP 2019',
    year: 2019,
    modelsTested: 'Bi-LSTM, ESIM, Decomposable Attention, BiDAF, QANet, GPT-2 (117M/345M)',
    prevalence: '23.89%',
    mechanismSnippet: 'The foundational Wallace et al. 2019 trigger attack establishing token gradient updates for general NLP tasks.',
  },
  {
    id: 'atk-110',
    name: 'Weak-to-Strong Jailbreaking',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Adversarial Triggers',
    venue: 'ICML 2025',
    year: 2025,
    modelsTested: 'Llama2 (7B/13B/70B), Vicuna (7B/13B), Baichuan2 (7B/13B), InternLM (7B/20B)',
    prevalence: '23.89%',
    mechanismSnippet: 'Uses tiny aligned model logits to compute guidance directions for triggering massive flagship targets.',
  },

  {
    id: 'atk-111',
    name: 'Best-of-N Prompt Sampling',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Paraphrase-Based Transfer',
    venue: 'arXiv',
    year: 2024,
    modelsTested: 'Claude 3.5 Sonnet/Opus, GPT-4o/mini, Gemini 1.5 Flash/Pro, Llama 3 8B, Circuit Breaking RR',
    prevalence: '2.65%',
    mechanismSnippet: 'Samples thousands of automated paraphrases with subtle temperature shifts, exploiting the long tail of safety variance.',
  },
  {
    id: 'atk-112',
    name: 'Semantic Mirror Jailbreak (SMJ)',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Paraphrase-Based Transfer',
    venue: 'arxiv',
    year: 2024,
    modelsTested: 'Llama-2-7b-chat, Vicuna-7b-v1.5, Guanaco-7b',
    prevalence: '2.65%',
    mechanismSnippet: 'Inverts negative lexical clauses into affirmative assertions without modifying core factual dependencies.',
  },
  {
    id: 'atk-113',
    name: 'TextFooler',
    family: 'Perturbation',
    category: 'Transfer Text Perturbations',
    leaf: 'Paraphrase-Based Transfer',
    venue: 'AAAI 2020',
    year: 2020,
    modelsTested: 'BERT, CNN, BiLSTM (SST-2, IMDB, AG’s News, Yelp, SNLI, MNLI)',
    prevalence: '2.65%',
    mechanismSnippet: 'Semantics-preserving word replacement identifying influential words and swapping with cosine-similar synonyms.',
  },
];

// Target LLM Vulnerability Matrix: 12 leaves x 8 target ecosystems
export const MODEL_ECOSYSTEMS = [
  'GPT-4 / 4o / o1',
  'Llama 2 / 3 / 3.1',
  'Claude 2 / 3 / 3.5',
  'Gemini / PaLM 2',
  'DeepSeek V3 / R1',
  'Qwen 1.5 / 2.5 / 3',
  'Vicuna / Open LMs',
  'LlamaGuard / Classifiers',
];

export const VULNERABILITY_MATRIX: { leaf: string; scores: number[] }[] = [
  { leaf: 'Adversarial Triggers', scores: [95, 98, 85, 80, 75, 90, 95, 88] },
  { leaf: 'Character Micro-Edits', scores: [85, 90, 80, 60, 50, 70, 85, 65] },
  { leaf: 'Paraphrase Transfer', scores: [90, 85, 92, 88, 60, 65, 75, 50] },
  { leaf: 'Benign Wrapper + Core', scores: [92, 95, 82, 85, 70, 88, 92, 75] },
  { leaf: 'Jailbreak Search & Opt', scores: [96, 92, 88, 82, 85, 90, 95, 80] },
  { leaf: 'Scenario Assembly', scores: [88, 90, 85, 80, 82, 85, 88, 60] },
  { leaf: 'Base64 / URL Obfuscation', scores: [90, 88, 85, 75, 65, 70, 85, 55] },
  { leaf: 'JSON / Code-Blocks', scores: [94, 90, 92, 88, 90, 88, 85, 65] },
  { leaf: 'Prefix-Suffix Wrappers', scores: [85, 88, 80, 75, 88, 85, 80, 70] },
  { leaf: 'DAN Composites', scores: [88, 92, 80, 82, 60, 78, 90, 45] },
  { leaf: 'Simple Overrides', scores: [80, 88, 70, 65, 60, 75, 85, 50] },
  { leaf: 'Persona Role-Play', scores: [85, 90, 85, 80, 70, 88, 85, 60] },
];

// Target Model Exposure Matrix (Research paper citations count: 6 Model Groups x 8 Categories)
export const EXPOSURE_MODELS = [
  'OpenAI (GPT-3.5 / 4 / 4o / o1)',
  'Anthropic (Claude 2 / 3 / 3.5)',
  'Google (PaLM 2 / Gemini 1.5 / 2.5)',
  'Meta (Llama 2 / 3 / 3.1 / Guard)',
  'Reasoning (DeepSeek R1 / Qwen3 / QwQ)',
  'Open Baselines (Vicuna / Mistral / Falcon)',
];

export const EXPOSURE_CATEGORIES = [
  'Plain Perturbations',
  'Transfer Text Perturbations',
  'Context Framing & Deception',
  'Fragment Assembly',
  'Encoding & Unicode Tricks',
  'Wrappers & Schemas',
  'Direct Override Patterns',
  'Role-Play & Templates',
];

export const EXPOSURE_PAPERS_MATRIX: number[][] = [
  [8, 24, 15, 11, 10, 8, 12, 6],  // OpenAI
  [3, 14, 10, 8,  6, 5,  5, 5],  // Anthropic
  [2, 12, 11, 7,  5, 4,  6, 4],  // Google
  [9, 25, 16, 10,  9, 7, 11, 6],  // Meta Llama
  [2, 18, 12, 8,  6, 6,  4, 3],  // DeepSeek / Qwen
  [9, 22, 14, 10,  8, 6, 13, 5],  // Open Baselines
];

// 6 Core Design Requirements
export const DESIGN_REQUIREMENTS = [
  {
    num: '01',
    title: 'Mechanism-First Placement',
    rule: 'Classification relies strictly on the observable bypass vector at inference time, independent of target hazard or output.',
  },
  {
    num: '02',
    title: 'One-to-One Mapping',
    rule: 'Deterministic taxonomy mapping: each cataloged attack instance resolves to exactly one primary atomic leaf mechanism.',
  },
  {
    num: '03',
    title: 'Consistent Splitting',
    rule: 'Every internal hierarchy branch divides on a single explicit operational axis without ambiguous overlap.',
  },
  {
    num: '04',
    title: 'Executability',
    rule: 'Every leaf in the taxonomy supports concrete, runnable, testable prompts with verifiable empirical outcomes.',
  },
  {
    num: '05',
    title: 'Prevalence-Aware',
    rule: 'Empirical literature and red-team prevalence directly guides sampling rates for representative evaluation suites.',
  },
  {
    num: '06',
    title: 'Complete Scope Coverage',
    rule: 'Represents all major published prompt manipulation families across single-turn inference-time attacks.',
  },
];
